const WISHES = [
  ["", "Chúc em năm 2025 thật nhiều niềm vui và hạnh phúc 💖. Mà anh nghĩ, nếu có thêm anh ở bên thì chắc em sẽ còn vui hơn nữa nhỉ? 😉"],
  ["", "Hy vọng nụ cười của em sẽ luôn nở rộ, vì nụ cười đó làm tim anh lỡ nhịp mãi không thôi 🌞."],
  ["", "Chúc em một năm mới trọn vẹn, mọi dự định đều thành công. Mà em có dự định nào cần thêm người đồng hành không? Anh xung phong nè! 😘"],
  ["", "Năm mới em nhớ giữ gìn sức khỏe và hạnh phúc nha. Vì em hạnh phúc thì anh mới yên lòng được 🌸."],
  ["", "Chúc em luôn tràn đầy năng lượng để theo đuổi những gì em yêu thích. Nếu cần động lực thì cứ nhớ là anh luôn ở đây cổ vũ em nha 💪."],
  ["", "Mong năm mới em sẽ không chỉ tự tin mà còn tựa vào anh nữa. Vì anh thì lúc nào cũng sẵn sàng làm chỗ dựa cho em 🌈."],
  ["", "Chúc em năm mới ngập tràn niềm vui và những bất ngờ dễ thương. Biết đâu một trong những bất ngờ đó chính là anh thì sao nhỉ? 🎁"],
  ["", "Hy vọng mỗi ngày của em trong năm 2025 đều đáng nhớ, và nếu được, anh muốn trở thành một phần trong đó ✨."],
  ["", "Chúc em luôn được yêu thương và trân trọng, đặc biệt là từ một người rất đặc biệt – chính là anh ❤️."],
  ["", "Mong em luôn lạc quan và mạnh mẽ, vì em chính là ánh mặt trời trong mắt anh 🌻."],
  ["", "Chúc em gặp được những người bạn tốt. Nhưng nếu cần một người đặc biệt hơn bạn, thì anh đây sẵn lòng! 🤝"],
  ["", "Hy vọng em đạt được mọi mục tiêu trong năm mới. Còn mục tiêu của anh là có thể khiến em cười thật nhiều đấy 🏆."],
  ["", "Chúc em luôn hạnh phúc và trân trọng chính mình. Còn anh sẽ trân trọng từng giây phút khi được ở cạnh em 💖."],
  ["", "Mong em tìm thấy niềm vui trong từng điều nhỏ nhặt. Còn niềm vui lớn của anh là khi thấy em mỉm cười 🌼."],
  ["", "Chúc em một năm mới tràn ngập yêu thương và sự ấm áp. Biết đâu trong đó, có cả tình cảm của anh dành cho em thì sao nhỉ? 🏠"],
  ["", "Hy vọng năm nay em có thêm nhiều trải nghiệm mới. Biết đâu, một trong những trải nghiệm đó là yêu anh chẳng hạn 🎨."],
  ["", "Chúc em thật mạnh mẽ, vượt qua mọi thử thách. Còn nếu mệt quá, cứ dựa vào anh, anh sẵn sàng làm bờ vai cho em 🦸‍♀️."],
  ["", "Mong em tìm thấy sự bình yên trong tâm hồn. Anh hy vọng được là người mang đến bình yên đó cho em 🧘‍♀️."],
  ["", "Chúc em thành công trong công việc, còn chuyện yêu đương, cứ để anh lo cho em nha 📈."],
  ["", "Hy vọng năm mới em luôn được yêu thương. Nếu cần thêm chút yêu thương, anh sẵn sàng dành cả thế giới này cho em 🛡️."],
];
